security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            json_login:
                username_path: email
                check_path: api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: api_refresh_token

    access_control:
         - { path: ^/api/auth/token/(login|refresh), roles: PUBLIC_ACCESS }
         - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [POST] }
         - { path: ^/api/posts, roles: PUBLIC_ACCESS, methods: [GET] }
         - { path: ^/api/users/me, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/api/posts, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
         - { path: ^/api/images, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext
