vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true